### ISSUE TITLE
执行程序输出的日志内容应该直接反馈到数据库会比较好。

### ISSUE THREAD

**Issue by dcb9** [dongzerun/dcms#1]
如果不直接返回到数据库里面，至少要提供相应的 hook 可以做这个事，内容里面应包含，程序退出的状态码、正确输出和错误输出。

因为添加任务不想在服务器上，那么看执行的日志其实也是不想上去的 :)

**Comment by dongzerun** [comment]
提供了webhook，任务完成的状态也会打到数据库日志表里的，可以做到自已的页面上。这个月底前我弄个页面吧。
