### ISSUE TITLE
可以添加一些更实用的功能

### ISSUE THREAD

**Issue by dcb9** [dongzerun/dcms#2]
- 计划任务上线时间，计划任务下线时间
- 对年和秒的支持

**Comment by dongzerun** [comment]
年和秒没必要支持，不通用吧？我是这么理解的

计划任务的下线时间？ 怎么理解，执行一次就废弃任务的订阅？ 这个可以做。

我还是倾向于下线要靠使用方。

**Comment by dcb9** [comment]
例如有个计划任务，要在凌晨开始 然后每小时执行一次，那业务人员还需要等到凌晨再去添加么？ 
同理下线的时候，假如要凌晨下线，还得人去下线就比较累。

其实这种任务还蛮多的，“执行周期” 对应 “什么时候到什么时候”。

秒和年的需求我以前没有过，但是这样多一层控制，就是给用户多一点的选择，我是这样认为的。

**Comment by dongzerun** [comment]
感谢感谢，理解了，我周末加上这个功能。

**Comment by dongzerun** [comment]
已经添加了，谢谢你的建议。

**Comment by dcb9** [comment]
:+1:
